name: Zypherous
icon: /assets/logo.webp
logo: /assets/logo.webp
homepage_logo: /assets/logo.webp
timezone: Europe/London
version: 11.4.3
testing: false
debug:
  oauth2: false
  pterodactyl: false
clusters: 1
database: sqlite://Zypherous.db
pterodactyl:
  domain: https://panel.example.com
  application_key: ptla_.................
  client_key: ptlc_.................
website:
  port: 3001
  secret: secret
  discord: https://discord.gg/example
  coins: Coins
maintenance:
  enabled: false
  allowAdmins: true
  message: We're currently performing scheduled maintenance. Please check back later.
api:
  client:
    accountSwitcher: true
    api:
      enabled: true
      code: secret
    j4r:
      enabled: false
      ads:
        - name: Example server 1
          invite: https://discord.gg/example
          id: "000000000000000000"
          coins: 200
        - name: Example server 2
          invite: https://discord.gg/example
          id: "000000000000000000"
          coins: 200
    bot:
      token: ""
      joinguild:
        _comment: >-
          The Discord bot must be in these servers and have invite permissions.
          Automatic guild joining will not work unless role packages are
          configured correctly. You can always just set it to a random role &
          package so that only this works.
        enabled: true
        guildid:
          - ""
      giverole:
        _comment: >-
          Auto-join must be enabled for this to work - or the user must already
          be in your Discord. This will give the user a role when they login.
        enabled: false
        guildid: your server id goes here mate
        roleid: your role id goes here mate
    passwordgenerator:
      signup: true
      note: Use this to disable registering on Zypherous.
      length: 24
    allow:
      newusers: true
      regen: true
      overresourcessuspend: false
      server:
        create: true
        modify: true
        delete: true
    referrals:
      _comment: Configure referral link limits, rewards, and the landing path.
      creator_reward: 100
      referee_reward: 250
      link: ""
      path: ref
      max_codes: 5
      max_uses_per_code: 0
    oauth2:
      _comment: >-
        Go to https://discord.dev/ and create an application to set up OAuth2.
        This is required for Zypherous to work. You must also set the redirect
        URL to the link below.
      id: your bot id
      secret: your bot secret
      link: https://example.com
      callbackpath: /callback
      prompt: true
      ip:
        trust x-forwarded-for: true
        block: []
        duplicate check: false
        _note: >-
          Anti-alt checks will not work if you are proxying through Cloudflare.
          This is due to the fact that Cloudflare does not pass the real IP
          address through the headers. If you are using Cloudflare, please
          disable this feature.
    google:
      enabled: true
      clientId: your client id
      clientSecret: your client secret
      callback: /auth/google/callback
      jwtSecret: your jwt secret
    ratelimits:
      /callback: 2
      /create: 1
      /delete: 1
      /modify: 1
      /updateinfo: 1
      /setplan: 2
      /admin: 1
      /regen: 1
      /renew: 1
      /api/userinfo: 1
    packages:
      default: default
      list:
        default:
          ram: 3072
          disk: 5120
          cpu: 150
          servers: 4
      rolePackages:
        note: >-
          This allows you to set a different plan/package to people who have a
          specific role however this requires the Discord bot to be configured
          and functioning. This is mainly used for Boost rewards.
        roleServer: ""
        roles: {}
    locations:
      "2":
        name: United Kingdom
        iso: GB
        pro: false
        show: true
    eggs:
      papermc:
        pro: false
        display: Minecraft - Paper
        minimum:
          ram: 1024
          disk: 1024
          cpu: 100
        maximum:
          ram: 6144
          disk: 20480
          cpu: 400
        info:
          egg: 1
          docker_image: ghcr.io/zenllc/java:21
          startup: >-
            java -Xms128M -XX:MaxRAMPercentage=95.0 -Dterminal.jline=false
            -Dterminal.ansi=true -jar {{SERVER_JARFILE}}
          environment:
            SERVER_JARFILE: server.jar
            BUILD_NUMBER: latest
            JAVA_ARGUMENTS: >-
              --add-modules=jdk.incubator.vector -XX:+UseG1GC
              -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200
              -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC
              -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4
              -XX:InitiatingHeapOccupancyPercent=15
              -XX:G1MixedGCLiveThresholdPercent=90
              -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32
              -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
              -Dusing.aikars.flags=https://mcflags.emc.gs/
              -Daikars.new.flags=true -XX:G1NewSizePercent=30
              -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M
              -XX:G1ReservePercent=20
          feature_limits:
            databases: 4
            backups: 4
      velocity:
        pro: false
        display: Velocity
        minimum:
          ram: 512
          disk: 128
          cpu: 50
        maximum:
          ram: 1024
          disk: 1024
          cpu: 125
        info:
          egg: 16
          docker_image: ghcr.io/zenllc/java:21
          startup: >-
            java -Xms128M -Xmx{{SERVER_MEMORY}}M {{JAVA_ARGUMENTS}} -jar
            {{SERVER_JARFILE}}
          environment:
            SERVER_JARFILE: server.jar
            VELOCITY_VERSION: latest
            JAVA_ARGUMENTS: >-
              -XX:+UseG1GC -XX:G1HeapRegionSize=4M
              -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled
              -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15
            BUILD_NUMBER: latest
          feature_limits:
            databases: 4
            backups: 4
      vanillabugrock:
        pro: false
        display: Vanilla Bedrock
        minimum:
          ram: 512
          disk: 128
          cpu: 50
        maximum:
          ram: 6144
          disk: 20480
          cpu: 400
        info:
          egg: 17
          docker_image: ghcr.io/parkervcp/yolks:debian
          startup: ./bedrock_server
          environment:
            BEDROCK_VERSION: latest
            LD_LIBRARY_PATH: .
            SERVERNAME: Server
            GAMEMODE: survival
            DIFFICULTY: easy
            CHEATS: "false"
          feature_limits:
            databases: 4
            backups: 4
      pmmpbugrock:
        pro: false
        display: PocketMineMP
        minimum:
          ram: 512
          disk: 128
          cpu: 50
        maximum:
          ram: 6144
          disk: 20480
          cpu: 400
        info:
          egg: 21
          docker_image: ghcr.io/parkervcp/yolks:debian
          startup: ./bin/php7/bin/php ./PocketMine-MP.phar --no-wizard
          environment:
            VERSION: PM5
          feature_limits:
            databases: 4
            backups: 4
    coins:
      enabled: true
      dailyReward: 150
      store:
        enabled: true
        ram:
          cost: 50
          per: 1024
        disk:
          cost: 750
          per: 2048
        cpu:
          cost: 2000
          per: 100
        servers:
          cost: 750
          per: 1
        packages:
          pro:
            name: Pro
            description: Perfect for small projects and testing
            cost: 1000
            highlight: false
            ram: 1
            cpu: 1
            disk: 2
            servers: 1
          pro-plus:
            name: Pro +
            description: Balanced resources for most applications
            cost: 4500
            highlight: false
            ram: 2
            cpu: 2
            disk: 4
            servers: 2
          ultimate:
            name: Ultimate
            description: High performance for demanding workloads
            cost: 8000
            highlight: false
            ram: 4
            cpu: 4
            disk: 8
            servers: 3
  afk:
    path: ws
    every: 60
    coins: 2
    enabled: true
resources:
  ram: 6144
  disk: 20480
  cpu: 400
  servers: 5
linkvertise:
  enabled: true
  coins: 150
  userid: "000000"
antivpn:
  note: >-
    For this to work, generate an API Key on https://proxycheck.io/. If you do
    not put a key, Zypherous will automatically disable anti-VPN.
  status: false
  APIKey: Proxycheck API Key
  whitelistedIPs:
    - IP address
whitelist:
  note: >-
    This allows only specific people to be able to login to the Zypherous
    dashboard. This does not affect your Panel.
  status: false
  users:
    - User ID
logging:
  _note: >-
    This is the 2nd-generation version of Zypherous's logging system. Please
    report any bugs on the GitHub (github.com/Zypherous/Zypherous). Thank you.
  status: true
  webhook: ""
  timeout_ms: 5000
  local:
    enabled: true
    file: logs/transactions.log
    max_size_kb: 512
  actions:
    user:
      signup: true
      create server: true
      gifted coins: true
      modify server: true
      buy servers: true
      buy ram: true
      buy cpu: truetrue
      buy disk: true
    admin:
      set coins: true
      add coins: true
      set resources: true
      set plan: truetrue
      create coupon: true
      revoke coupon: true
      remove account: true
      view ip: true
    system:
      worker online: true
      worker exit: true
      worker fork: true
      workers reboot: true
